### PR TITLE
Fallback mechanism for resource selection

### PR DESCRIPTION
**Pull request by wpdebruin**
This PR adds a fallback mechanism for selecting resource files. Resources can be in the form
   lang_COUNTRYCODE_extrainfo
which means a resource named myResource will only be loaded if myResource_lang_COUNTRYCODE_extrainfo.properties is a valid path.
This PR falls back to less selective property files in this order:
- myResource_lang_COUNTRYCODE_extrainfo.properties
- myResource_lang_COUNTRYCODE.properties
- myResource_lang.properties
- myResource.properties
- myResource_defaultlocale.properties

By default the cbi18n is not modified. The above behaviour can be added by the new config option 		i18n.smartBundleSelection = true

This PR is quite useful because it makes localization of the cbvalidation module a lot more reliable and easier.

### CODE REVIEW

**Comment by wpdebruin** [comment]
My local tests are all OK, but here the tests fail? I don't understand why.

**Comment by elpete** [comment]
Does it pass when you run `box task run taskfile=build/Build target=run :version=v1.6.0 :projectName=cbi18n` locally?

**Comment by elpete** [comment]
Also, the Adobe engines are giving this error:

**Comment by lmajano** [comment]
BOX-64
cbi18n : Fallback mechanism for resource selection

**Comment by lmajano** [comment]
https://ortussolutions.atlassian.net/browse/BOX-64

**Comment by wpdebruin** [comment]
replaced by pr #32

**Pull request closed without merging**
